// packages/admin/src/views/reservation/index.vue
<template>
  <div class="page-container">
    <div class="page-header">
      <span class="page-title">预订管理</span>
    </div>

    <!-- 筛选 / Filter -->
    <a-space style="margin-bottom: 16px">
      <a-radio-group v-model:value="filterStatus" button-style="solid" @change="loadList">
        <a-radio-button :value="null">全部</a-radio-button>
        <a-radio-button :value="0">待确认</a-radio-button>
        <a-radio-button :value="1">已确认</a-radio-button>
        <a-radio-button :value="2">已取消</a-radio-button>
        <a-radio-button :value="3">已完成</a-radio-button>
      </a-radio-group>
      <a-date-picker v-model:value="filterDate" placeholder="按日期筛选" @change="loadList" />
    </a-space>

    <a-table :data-source="list" :columns="columns" :loading="loading" row-key="id">
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'dateTime'">
          <div>{{ record.reservationDate }}</div>
          <div style="color: #999; font-size: 12px">{{ record.reservationTime }}</div>
        </template>
        <template v-if="column.key === 'contact'">
          <div>{{ record.contactName }}</div>
          <div style="color: #999; font-size: 12px">{{ record.contactPhone }}</div>
        </template>
        <template v-if="column.key === 'status'">
          <a-tag :color="statusColor(record.status)">{{ statusText(record.status) }}</a-tag>
        </template>
        <template v-if="column.key === 'action'">
          <a-space v-if="record.status === 0">
            <a-button
              type="primary"
              size="small"
              style="background: #27ae60; border: none"
              @click="updateStatus(record.id, 1)"
              >确认</a-button
            >
            <a-button danger size="small" @click="updateStatus(record.id, 2)">取消</a-button>
          </a-space>
          <a-button v-else-if="record.status === 1" size="small" @click="updateStatus(record.id, 3)"
            >标记完成</a-button
          >
          <span v-else style="color: #ccc">-</span>
        </template>
      </template>
    </a-table>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import dayjs from 'dayjs'
import { getReservationList, updateReservationStatus, type Reservation } from '@/api/reservation'

const list = ref<Reservation[]>([])
const loading = ref(false)
const filterStatus = ref<number | null>(null)
const filterDate = ref<any>(null)

const columns = [
  { title: '预订日期/时段', key: 'dateTime', width: 130 },
  { title: '人数', dataIndex: 'peopleCount', width: 70 },
  { title: '联系人', key: 'contact', width: 130 },
  { title: '备注', dataIndex: 'remark', ellipsis: true },
  {
    title: '提交时间',
    dataIndex: 'createTime',
    width: 160,
    customRender: ({ text }: any) => text?.replace('T', ' ').substring(0, 16),
  },
  { title: '状态', key: 'status', width: 90 },
  { title: '操作', key: 'action', width: 150 },
]

async function loadList() {
  loading.value = true
  const params: { status?: number; date?: string } = {}
  if (filterStatus.value != null) params.status = filterStatus.value
  if (filterDate.value) params.date = dayjs(filterDate.value).format('YYYY-MM-DD')
  try {
    list.value = await getReservationList(params)
  } catch (e) {
    console.error(e)
  } finally {
    loading.value = false
  }
}

async function updateStatus(id: number, status: number) {
  try {
    await updateReservationStatus(id, status)
    message.success('状态已更新')
    loadList()
  } catch (e) {
    console.error(e)
  }
}

function statusText(s: number) {
  return ['待确认', '已确认', '已取消', '已完成'][s] || '-'
}

function statusColor(s: number) {
  const map: Record<number, string> = { 0: 'orange', 1: 'green', 2: 'default', 3: 'blue' }
  return map[s] || 'default'
}

onMounted(loadList)
</script>

<style scoped>
.page-container {
  background: #fff;
  padding: 24px;
  border-radius: 8px;
}
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}
.page-title {
  font-size: 18px;
  font-weight: bold;
  color: #1a1a2e;
}
</style>

// packages/admin-react/src/views/reservation/index.tsx
import { useState, useEffect } from 'react'
import { Table, Tag, Radio, DatePicker, Space, Button, message } from 'antd'
import dayjs from 'dayjs'
import request from '../../utils/request'
import styles from '../page.module.less'

const statusText = (s: number) => ['待确认', '已确认', '已取消', '已完成'][s] || '-'
const statusColor: Record<number, string> = { 0: 'orange', 1: 'green', 2: 'default', 3: 'blue' }

export default function Reservation() {
  const [list, setList] = useState([])
  const [loading, setLoading] = useState(false)
  const [filterStatus, setFilterStatus] = useState<number | null>(null)
  const [filterDate, setFilterDate] = useState<any>(null)

  const columns = [
    {
      title: '预订日期/时段',
      key: 'dateTime',
      width: 130,
      render: (_: any, r: any) => (
        <>
          <div>{r.reservationDate}</div>
          <div className={styles.subText}>{r.reservationTime}</div>
        </>
      ),
    },
    { title: '人数', dataIndex: 'peopleCount', width: 70 },
    {
      title: '联系人',
      key: 'contact',
      width: 130,
      render: (_: any, r: any) => (
        <>
          <div>{r.contactName}</div>
          <div className={styles.subText}>{r.contactPhone}</div>
        </>
      ),
    },
    { title: '备注', dataIndex: 'remark', ellipsis: true },
    {
      title: '提交时间',
      dataIndex: 'createTime',
      width: 160,
      render: (text: string) => text?.replace('T', ' ').substring(0, 16),
    },
    {
      title: '状态',
      key: 'status',
      width: 90,
      render: (_: any, r: any) => (
        <Tag color={statusColor[r.status]}>{statusText(r.status)}</Tag>
      ),
    },
    {
      title: '操作',
      key: 'action',
      width: 150,
      render: (_: any, r: any) => {
        if (r.status === 0) {
          return (
            <Space>
              <Button type="primary" size="small" className={styles.confirmBtn} onClick={() => updateStatus(r.id, 1)}>
                确认
              </Button>
              <Button danger size="small" onClick={() => updateStatus(r.id, 2)}>取消</Button>
            </Space>
          )
        }
        if (r.status === 1) {
          return <Button size="small" onClick={() => updateStatus(r.id, 3)}>标记完成</Button>
        }
        return <span className={styles.placeholder}>-</span>
      },
    },
  ]

  async function loadList() {
    setLoading(true)
    const params: any = {}
    if (filterStatus != null) params.status = filterStatus
    if (filterDate) params.date = dayjs(filterDate).format('YYYY-MM-DD')
    try {
      const data: any = await request.get('/admin/reservation/list', { params })
      setList(data)
    } catch (e) { console.error(e) } finally { setLoading(false) }
  }

  async function updateStatus(id: number, status: number) {
    try {
      await request.put(`/admin/reservation/${id}/status`, { status })
      message.success('状态已更新')
      loadList()
    } catch (e) { console.error(e) }
  }

  useEffect(() => { loadList() }, [filterStatus, filterDate])

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <span className={styles.title}>预订管理</span>
      </div>

      <Space className={styles.filterBar}>
        <Radio.Group
          value={filterStatus}
          buttonStyle="solid"
          onChange={e => setFilterStatus(e.target.value)}
        >
          <Radio.Button value={null}>全部</Radio.Button>
          <Radio.Button value={0}>待确认</Radio.Button>
          <Radio.Button value={1}>已确认</Radio.Button>
          <Radio.Button value={2}>已取消</Radio.Button>
          <Radio.Button value={3}>已完成</Radio.Button>
        </Radio.Group>
        <DatePicker value={filterDate} onChange={setFilterDate} placeholder="按日期筛选" />
      </Space>

      <Table dataSource={list} columns={columns} loading={loading} rowKey="id" />
    </div>
  )
}
